### ISSUE TITLE
Update Broccoli

### ISSUE THREAD

**Issue by astucieuxzephyr** [talon/keystone-ember-demo#1]
Hello, could you add some information to make this app work ?
I tried the following commands 

- bower install
- npm install -g ember

Then I get the following error : 

```
DEPRECATION: Brocfile.js has been deprecated in favor of ember-cli-build.js. **Please see the transition guide**: https://github.com/ember-cli/ember-cli/blob/master/TRANSITION.md#user-content-brocfile-transition.
Cannot find module 'ember-cli/lib/broccoli/ember-app'
Error: Cannot find module 'ember-cli/lib/broccoli/ember-app'
 ...
```

So, I followed the instructions of the guide on github, and I create the ember-cli-build.js file with the settings of the Brocfile.js file.

But then, when I try an `ember test` or `ember build`, i get the following error :  

```
Could not require 'ember-cli-build.js': Cannot find module 'ember-cli/lib/broccoli/ember-app'
Error: Could not require 'ember-cli-build.js': Cannot find module 'ember-cli/lib/broccoli/ember-app'
...
```
Do you have an idea of what I should do then ?

**Comment by talon** [comment]
@astucieuxzephyr I'm sorry but this repo is extremely out of date and I have lost interest in maintaining it. I think Keystone ultimately landed on using React anyway. Sorry I can't be of much help here! I'll remove the repo to avoid future confusion
